name: "A Github Action for deploying to AWS EKS Kubernetes cluster by running the helmfile command"
description: "It can also use aws-iam-authenticator to authenticate. You can also specify a kubeconfig environment variable too."
author: Sam
branding:
  icon: 'chevrons-up'  
  color: 'orange'
inputs:
  command:
    description: "Your command (helm or helmfile)"
    required: true
outputs:
  result:
    description: "Result returned from helmfile/helm"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}